title:              "Marketing    [Emergency-Card]"
tagline:            "<br><br>위기에 빠진 마케터 손에 아이디어 한 장,"
email:              "deepdiver@kakao.com"
description:        "머리칼 쥐어뜯는 당신의 손에 아이디어 카드 한 장 쥐어드립니다. 마케팅 레퍼런스, 브랜드, 밈, 마케팅 책 리뷰를 다룹니다"
author:             "비상대책본부장"
baseurl:            "/"
url:                "https://sticky-factory.github.io"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.png"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: sticky-factory
